/* FEEL FREE TO EDIT. THIS FILE IS AUTOMATICALLY GENERATED */
use serde::{Deserialize, Serialize};
use serde_valid::Validate;
#[derive(strum_macros::EnumString, Default, Debug, Clone, Serialize, Deserialize, Validate)]
#[strum(serialize_all = "snake_case")]
pub enum QuotedSubscriptionChangeOption {
    #[default]
    EndOfTerm,
    SpecificDate,
    Immediately,
}
